# Default state for all rules
default: true

# MD004/ul-style : Unordered list style
MD004:
  style: "sublist"

# MD024/no-duplicate-heading
MD024:
  allow_different_nesting: true
  siblings_only: true

# References:
# https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md
# https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml
